[package]
name = "elysees"
version = "0.0.2"
authors = ["Jad Elkhaleq Ghalayini", "The Servo Project Developers"]
license = "MIT/Apache-2.0"
repository = "https://gitlab.com/rain-lang/elysees"
description = "A fork of triomphe::Arc with some extra functionality. Currently just adds a getter for the refcount."
keywords = ["arc", "ffi", "sync", "data-structure"]
categories = ["concurrency", "data-structures"]

[features]
std = []
default = ["serde", "stable_deref_trait", "std"]

[dependencies]
memoffset = "0.5.3"
serde = { version = "1.0", default-features = false, optional = true }
stable_deref_trait = { version = "1.1.1", default-features = false, optional = true }
